# Generated by Django 4.1 on 2022-09-10 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='videos', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
    ]
