# Generated by Django 4.1 on 2022-09-21 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Detection', '0003_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
